In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import r2_score, mean_absolute_error, accuracy_score

In [10]:
df = pd.read_csv('steam_games_selected_features.csv')
df.head()

,name,price_usd,price_tier,value_score_calc,quality_score,age_by_years,categories_count,languages_count,peak_ccu,log_reviews,genre_casual,genre_count,full_audio_languages_count,is_indie,average_playtime_forever,cat_single_player
0,it's always monday,1.99,Budget,39.64,78.89,9.705681,2,1,0.000000,5.669881,0,3,1,1,265,1
1,The Agency of Anomalies: Cinderstone Orphanage...,19.99,Mid-range,5.00,100.00,9.708419,2,1,0.000000,2.564949,1,2,1,0,0,1
2,CRAFT: Work VR Shop,6.99,Budget,7.15,50.00,9.664613,6,1,0.000000,2.197225,0,3,1,1,0,1
3,Sonya: The Great Adventure,6.99,Budget,10.35,72.36,9.314168,5,6,0.693147,5.298317,1,3,2,1,215,1
4,Queen's Quest 2: Stories of Forgotten Past,14.99,Mid-range,6.08,91.20,9.489391,5,9,1.386294,5.525453,1,2,2,0,402,1

In [11]:
features = [
    'quality_score',
    'age_by_years',
    'categories_count',
    'languages_count',
    'peak_ccu',
    'log_reviews',
    'genre_casual',
    'genre_count',
    'full_audio_languages_count',
    'is_indie',
    'average_playtime_forever',
    'cat_single_player'
]

X = df[features]
y = df['value_score_calc']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 46148
Testing samples: 11537

In [13]:
model1 = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42)
model1.fit(X_train, y_train)

predictions1 = model1.predict(X_test)

print("Model 1 Evaluation")
print("R2 Score:", r2_score(y_test, predictions1))
print("Mean Absolute Error (MAE):", mean_absolute_error(y_test, predictions1))

Model 1 Evaluation
R2 Score: 0.22784014652612483
Mean Absolute Error (MAE): 12.04916164648509

In [14]:
output_df1 = pd.DataFrame({
    'Actual Value Score': y_test.values[:10],
    'Predicted Value Score': predictions1[:10].round(2)
})
output_df1

   Actual Value Score  Predicted Value Score
0                2.25                   6.16
1                7.52                  12.98
2                2.70                  35.42
3                4.72                  12.54
4               25.25                  12.36
5               10.01                  27.90
6               21.93                  29.59
7               17.64                  20.84
8                6.15                  10.22
9                6.35                   9.52

In [15]:
y_tier = df['price_tier']

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X, y_tier, test_size=0.2, random_state=42)

model2 = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
model2.fit(X_train_c, y_train_c)

predictions2 = model2.predict(X_test_c)

print("Model 2  Evaluation")
print("Accuracy Score:", accuracy_score(y_test_c, predictions2))

Model 2  Evaluation
Accuracy Score: 0.7803588454537574

In [16]:
output_df2 = pd.DataFrame({
    'Actual Price Tier': y_test_c.values[:10],
    'Predicted Price Tier': predictions2[:10]
})
output_df2

  Actual Price Tier Predicted Price Tier
0         Mid-range            Mid-range
1         Mid-range               Budget
2         Mid-range               Budget
3         Mid-range               Budget
4            Budget               Budget
5            Budget               Budget
6            Budget               Budget
7            Budget               Budget
8         Mid-range               Budget
9            Budget               Budget